name: "Terraform launch instance install Jenkins"

on:
  push:
    branches:
      - main  # Runs on push to main branch
 
    paths:
        - '.github/workflows/test.yml'   
jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change as needed

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform (Only on main branch)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

