name: Terraform AWS Deployment

on:
  push:
    branches:
      - main  # Run on every push to the main branch
    paths:
     - '.Github/workflows/jenkins.yml'

jobs:
  terraform:
    name: Deploy AWS Infra with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraformgit
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
