name: Terraform Deployment


on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '.github/workflows/test.yml'
  workflow_dispatch:  # ✅ Allows manual triggering from GitHub UI

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Terraform Files Exist
        run: ls -la ./jenkins  # ✅ सही फोल्डर नाम

      - name: Debug Repository Structure
        run: ls -R  # ✅ Debugging Step

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./jenkins  
        run: terraform init

      - name: Validate Terraform Configuration
        working-directory: ./jenkins
        run: terraform validate

      - name: Plan Terraform Deployment
        working-directory: ./jenkins
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes
        working-directory: ./jenkins
        run: terraform apply -auto-approve tfplan
