on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Terraform Files Exist
        run: ls -la
        working-directory: ./terraform  # 🔥 Ensure this is the correct path!

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform  # 🔥 Make sure this path is correct!

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
