name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip "cd /your-app && git pull && systemctl restart your-app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
